# Generated by Django 5.2.6 on 2025-09-25 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_scope_options_alter_scope_is_main_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'verbose_name': 'Тематика статьи', 'verbose_name_plural': 'Тематики статьи'},
        ),
        migrations.AddField(
            model_name='article',
            name='tag_names',
            field=models.ManyToManyField(through='articles.Scope', to='articles.tag', verbose_name='Разделы'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='tag_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='articles.tag', verbose_name='Раздел'),
        ),
    ]
