# Generated by Django 5.2.6 on 2025-09-25 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_scope_options_article_tag_names_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='tag_names',
            new_name='scopes',
        ),
    ]
