# Generated by Django 5.2.6 on 2025-09-25 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_rename_tag_names_article_scopes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scope',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope', to='articles.article', verbose_name='Название статьи'),
        ),
    ]
