# Generated by Django 5.2.6 on 2025-09-25 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_rename_tag_name_tag_name_alter_scope_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scope',
            old_name='title',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='scope',
            old_name='tag_name',
            new_name='tag',
        ),
    ]
