# Generated by Django 5.2.7 on 2025-10-09 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Measurement',
        ),
    ]
