# примеры API-запросов

@baseUrl = http://127.0.0.1:8000/api

# получение датчиков
GET {{baseUrl}}/sensors/
Content-Type: application/json

###

# создание датчика
POST {{baseUrl}}/sensors/
Content-Type: application/json

{
  "name": "ESP32",
  "description": "Один датчик на кухне за холодильником"
}

###

# обновление датчика
PATCH {{baseUrl}}/sensors/10/
Content-Type: application/json

{
  "description": "Перенес датчик на балкон"
}

###

# добавление измерения
POST {{baseUrl}}/measurements/
Content-Type: application/json

{
  "sensor": 7,
  "temperature": 22.3
}

###

# добавление измерения
GET {{baseUrl}}/measurements/
Content-Type: application/json

###

# получение информации по датчику
GET {{baseUrl}}/sensors/6/
Content-Type: application/json

